version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/fuzz"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    open-pull-requests-limit: 10
